# Generated by Django 4.2.5 on 2024-03-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
            ],
            options={
                "ordering": ["nome", "estado"],
            },
        ),
        migrations.CreateModel(
            name="Estudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("matricula", models.CharField(max_length=255)),
                ("data_nascimento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("atualizado_em", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estagio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=255)),
                ("data_inicio", models.DateField(verbose_name="Data de início")),
                ("data_termino", models.DateField(blank=True)),
                ("carga_horaria", models.IntegerField()),
                (
                    "estudante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.estudante",
                    ),
                ),
            ],
        ),
    ]
