# Generated by Django 4.2.5 on 2024-03-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudante",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
